### ISSUE TITLE
Some improvement in experiments.tsv

### ISSUE THREAD

**Issue by wlllssd** [UWHustle/Efficiently-Searching-In-Memory-Sorted-Arrays#7]
Problem:
If we clone and run directly, the would print 'algorithm InterpolationSearch not found'
It is because in *benchmark.h*
tuple: **"is" <-> "InterpolationSearch"**
but in *experiments.tsv*
the SearchAlgorithm uses **"InterpolationSearch"**
As a result, it doesn't work

one possible solution is
change all **"InterpolationSearch"** to **"is"** in *experiments.tsv*

I hope you can improve it and help others
Thank you

**Comment by johnchronis** [comment]
Thank you @wlllssd for catching this mistake and taking the time to create an issue!

I have updated the experiments.csv to use the correct algorithm name.
